### ISSUE TITLE
DocBERT model weights

### ISSUE THREAD

**Issue by stefan-it** [castorini/hedwig#12]
Dear maintainers and authors :)

I just found the [DocBERT](https://arxiv.org/abs/1904.08398) paper on arxiv and would really like to know, if you plan to share/release the weights and config file - I would really like to load them with `pytorch-pretrained-BERT` and play around with the model :heart: 

Thanks in advance,

Stefan

**Comment by achyudh** [comment]
Hi Stefan!

Thanks for your interest in our project! The model weights are quite large, and we would not be able to upload them here. While we are currently looking into alternate options, it doesn't take a lot of time to fine-tune BERT using our code on the datasets mentioned in our paper. Once you set up the project based on [these instructions](https://github.com/castorini/hedwig/blob/master/README.md), you can reproduce our results using the steps mentioned [here](https://github.com/castorini/hedwig/tree/master/models/bert).

**Comment by Ashutosh-Adhikari** [comment]
Looks like this has been adressed for now. @stefan-it feel free to reopen the issue if the need be.
