### ISSUE TITLE
BertForSequenceClassification prediction.

### ISSUE THREAD

**Issue by abhranil08** [castorini/hedwig#23]
Can I get any sample code for training a SequenceClassification model and then the prediction?

**Comment by daemon** [comment]
Here's the DocBERT [README](https://github.com/castorini/hedwig/tree/master/models/bert) and [training code](https://github.com/castorini/hedwig/blob/master/models/bert/__main__.py#L101).

**Comment by srzarin** [comment]
Which is the prediction code for the docbert model?
