### ISSUE TITLE
Reproducing Setup and README steps

### ISSUE THREAD

**Issue by gauchm** [castorini/hedwig#3]
Playing around with the package, I managed to run Kim-CNN but had some minor hiccups:

**README**
- The Conv-RNN and Char-CNN links are dead
- I needed to do `conda activate castor` instead of `source activate castor`
- The README wants me to do `nltk.download()`, but I don't think that's needed? I didn't do it because I didn't know which datasets to use, and so far it worked...
- There's no `get_trec_eval.sh` in utils/

**Running a Model**
- The model READMEs tell me to run `python -m modelname ...`, but I need to run `python -m models.modelname ...` in the Hedwig directory.
- I had to manually install `tensorboardX` to run Kim-CNN (used in `common/trainers/classification_trainer.py`)
- The models try to load a `Google-News-vectors-negative300.txt` word2vec vector, but there's only a binary one in `../Castor-data/embeddings/word2vec/` I had to convert it manually. (Afterwards I realized there's an arg for that, maybe I could have changed `--word-vectors-file` to .bin...)
- `python -m kim_cnn --trained_model ...` should be `... --trained-model ...`

**Comment by achyudh** [comment]
Thanks a lot for reporting the issues with the README files. We need to fix README files for all models, along with the project README. For starters, some model README files contain datasets that have been removed from the project.

**Comment by lintool** [comment]
@gauchm should we consider this resolved, or is there more to do here? If resolved, close issue?

**Comment by gauchm** [comment]
I checked, it's all resolved.
