### ISSUE TITLE
Reg-LSTM

### ISSUE THREAD

**Issue by daleangus** [castorini/hedwig#53]
Who can this model be attributed? I would really appreciate a quick response because I am finishing a project report.

**Comment by daemon** [comment]
A simple cite of https://www.aclweb.org/anthology/N19-1408/ would be
```
Ashutosh Adhikari, Achyudh Ram, Raphael Tang, and Jimmy Lin. 2019. Rethinking Complex Neural Network Architectures for Document Classification. In NAACL.
```
