### ISSUE TITLE
Bert Inference Issue 

### ISSUE THREAD

**Issue by vivekam101** [castorini/hedwig#64]
Thanks for the repo.. Can you guys please check for below error

$ python -m models.bert --dataset Reuters  --model bert-base-uncased --max-seq-length 256 --batch-size 16 --lr 2e-5 --epochs 30 --trained-model model_checkpoints/bert/Reuters/2020-06-21_10-03-33.pt 

***
Device: CUDA
Number of GPUs: 4
FP16: False
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/vivek/hedwig/models/bert/__main__.py", line 122, in <module>
    warmup_steps=args.warmup_proportion * num_train_optimization_steps)
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

***

Please check

**Comment by achyudh** [comment]
Hello @vivekam101! Thanks for pointing this issue out. Looks like there is a bug in scheduler initialization when loading a trained BERT model. Please let me know if the changes in https://github.com/castorini/hedwig/pull/65 fix this for you.
